### PR TITLE
logging context

### PR DESCRIPTION
**Pull request by imakunin**

### CODE REVIEW

**Comment by Hoxo** [comment]
But what is the main purpose of such changes? We should see these fields as context in actual logging UI, but if we put them in message, it'll become unreadable

**Comment by imakunin** [comment]
> But what is the main purpose of such changes? We should see these fields as context in actual logging UI, but if we put them in message, it'll become unreadable

I think we should log everything from the `LoginContext`, otherwise it is not needed :). But I don't want to place `%X` in the pattern, because there are things we don't need there right now (in library threads). Therefore, I have explicitly indicated the keys, which we add ourselves.

**Comment by Hoxo** [comment]
> I think we should log everything from the LoginContext, otherwise it is not needed :)
We already get context in UI, so why do we need another text representation?

**Comment by Hoxo** [comment]
>  I thought that we write logs to a file, which is then parsed and goes to the Logging Service in a structured form.

You're right about that. But these logs are written to file in JSON format with all MDC entities, so we don't need to explicitly set them. If you look to log4j2.yaml files, you'll see that there's RollingFile appender which is using JSONLayout. That is, we don't need to parse log string with regexp.

**Pull request closed without merging**
